# Generated by Django 5.0.2 on 2024-02-27 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_Backend', '0002_rename_user_user_registrations'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_registrations',
            name='birth_date',
            field=models.DateField(default='0001-01-01'),
        ),
    ]
