# Generated by Django 5.0.2 on 2024-02-28 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_Backend', '0007_alter_user_registrations_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_registrations',
            name='firsName',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='user_registrations',
            name='lastName',
            field=models.CharField(),
        ),
    ]
