# Generated by Django 5.0.2 on 2024-05-02 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_Backend', '0009_alter_user_registrations_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_registrations',
            name='birth_date',
        ),
    ]
