# Generated by Django 5.0.2 on 2024-05-02 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_Backend', '0010_remove_user_registrations_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_registrations',
            name='idNumber',
            field=models.CharField(unique=True),
        ),
    ]
