# Generated by Django 5.0.2 on 2024-05-12 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_Backend', '0011_alter_user_registrations_idnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_registrations',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
