# Generated by Django 5.0.2 on 2024-05-12 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_Backend', '0012_alter_user_registrations_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_registrations',
            name='is_active',
        ),
    ]
